Document: ignoreconfig
Title: Debian ignoreconfig Manual
Author: <insert document author here>
Abstract: This manual describes what ignoreconfig is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ignoreconfig/ignoreconfig.sgml.gz

Format: postscript
Files: /usr/share/doc/ignoreconfig/ignoreconfig.ps.gz

Format: text
Files: /usr/share/doc/ignoreconfig/ignoreconfig.text.gz

Format: HTML
Index: /usr/share/doc/ignoreconfig/html/index.html
Files: /usr/share/doc/ignoreconfig/html/*.html
